### ISSUE TITLE
Language and version

### ISSUE THREAD

**Issue by thingNumber1** [bopoda/robots-txt-parser#42]
Hi

What is the language in the readme file and why? Why not to use a more common language, like english?

Also, I see there is a 2.0 version but is not the same as the one in the master. Why?

Greetings

**Comment by bopoda** [comment]
Hi @thingNumber1,

1. readme has been written a long time ago and i did not think about language. I agree with you we should use english only. Later i will update readme and all comments if there any other language uses. Now i don`t  have enough time.
2. v2.0 is stable release where performance of RobotsTxtParser has been improved. master `branch` can contain any more commits than release. `master` is also always should be stable (otherwise changes shouldn't be in `master`). There are minor changes in master ( for example your commit with typo) at the moment. I do not think that we should create release for such small changes.

Next release (for example v2.1) will be when `master` will contain some significant improvements.

Please write if something else. Thanks for feedback.

**Comment by thingNumber1** [comment]
Oh, I get it.  =D

**Comment by bopoda** [comment]
Resolved by https://github.com/bopoda/robots-txt-parser/pull/45
